const EMAIL_CHANGED = 'EMAIL_CHANGED';
const WALLET_CHANGED = 'WALLET_CHANGED';
const NAME_CHANGED = 'NAME_CHANGED';
const ADD_EXPENSE = 'ADD_EXPENSE';

export { EMAIL_CHANGED, WALLET_CHANGED, NAME_CHANGED, ADD_EXPENSE };
