const EMAIL_CHANGED = 'EMAIL_CHANGED';
const WALLET_CHANGED = 'WALLET_CHANGED';
const NAME_CHANGED = 'NAME_CHANGED';
const ADD_EXPENSE = 'ADD_EXPENSE';
const DELETE_EXPENSE = 'DELETE_EXPENSE';
const EDIT_EXPENSE = 'EDIT_EXPENSE';
const SAVE_EDIT = 'SAVE_EDIT';
const EDIT = 'EDIT';

export { EMAIL_CHANGED, WALLET_CHANGED,
  NAME_CHANGED, ADD_EXPENSE, DELETE_EXPENSE,
  EDIT_EXPENSE, SAVE_EDIT, EDIT };
